title: Huong Nguyen
description: Portfolio Website
url: https://github.com/huongntn/portfolio-website
theme: null
permalink: pretty
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md

include:
  - assets
